services:
  mysql:
    container_name: mysql-jpa
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #      - MYSQL_USER=root
      #      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    #    volumes:
    #      - ./data/mysql:/data/mysql
      - MYSQL_TCP_PORT=3308
    ports:
      - "3308:3308"
    networks:
      - mysql-jpa2

networks:
  mysql-jpa2:
    driver: bridge
