spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_schema?createDatabaseIfNotExist=true
    username: root
    password: Stefan0987
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
#    hibernate:
#      ddl-auto: create-drop
  liquibase:
    change-log: classpath:liquidbase-changelog.xml
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
logging:
  level:
    org:
      hibernate:
        tool:
          hbm2ddl: 'DEBUG'
      springframework:
        web: 'INFO'

server:
  error:
    include-message: 'always'
    include-binding-errors: 'always'

app:
  uploadDir: './data/productImages/'
  cartCleanup:
    scheduling:
      cron: '0 0 0 * * *'


